### ISSUE TITLE
No access to inception model for birds

### ISSUE THREAD

**Issue by MaxyLee** [hanzhanggit/StackGAN-inception-model#11]
Hi, there. I have no access to the inception model for birds on [google drive](https://drive.google.com/open?id=0B3y_msrWZaXLMzNMNWhWdW0zVWs). I've requested many times but have not yet gotten access. Can you please provide another download link? Thanks!

**Comment by priyankaupadhyay090** [comment]
> Hi, there. I have no access to the inception model for birds on [google drive](https://drive.google.com/open?id=0B3y_msrWZaXLMzNMNWhWdW0zVWs). I've requested many times but have not yet gotten access. Can you please provide another download link? Thanks!

Hey did you find the inception model for birds?

**Comment by iwldzt3011** [comment]
> > Hi, there. I have no access to the inception model for birds on [google drive](https://drive.google.com/open?id=0B3y_msrWZaXLMzNMNWhWdW0zVWs). I've requested many times but have not yet gotten access. Can you please provide another download link? Thanks!
> 
> Hey did you find the inception model for birds?

Hey did you find the inception model for birds?

**Comment by MaxyLee** [comment]
Not yet😭

**Comment by iwldzt3011** [comment]
> Not yet😭

那怎么办，我模型跑完了发现不能评估。。

**Comment by MaxyLee** [comment]
> > Not yet😭
> 
> 那怎么办，我模型跑完了发现不能评估。。

I suggest that you train an inception model yourself, share it, and close this issue. 加油😂😂😂

**Comment by iwldzt3011** [comment]
> > > Not yet😭
> > 
> > 
> > 那怎么办，我模型跑完了发现不能评估。。
> 
> I suggest that you train an inception model yourself, share it, and close this issue. 加油😂😂😂

是的，我现在正在用inception v3的预训练模型微调CUB 200，但是我不确定能够成功。。

**Comment by priyankaupadhyay090** [comment]
> > Hi, there. I have no access to the inception model for birds on [google drive](https://drive.google.com/open?id=0B3y_msrWZaXLMzNMNWhWdW0zVWs). I've requested many times but have not yet gotten access. Can you please provide another download link? Thanks!
> 
> Hey did you find the inception model for birds?

I finally found the link which works:

https://drive.google.com/file/d/0B3y_msrWZaXLMzNMNWhWdW0zVWs/view?resourcekey=0-gBxxw4fU6ikmNtkfFSQALw

**Comment by MaxyLee** [comment]
https://drive.google.com/file/d/0B3y_msrWZaXLMzNMNWhWdW0zVWs/view?resourcekey=0-gBxxw4fU6ikmNtkfFSQALw

Thanks to @priyankaupadhyay090

**Comment by rishabh004-ai** [comment]
@MaxyLee I am facing some issues in loading the model from the checkpoint. Which version of pytorch/tensorflow did you use for finetuning?

Can you share the code for loading the inceptionnet for CUB dataset.
